//* Copyright (c) 2010 Scott A. Crosby. <scott@sacrosby.com>
//
//Permission is hereby granted, free of charge, to any person obtaining a copy of
//this software and associated documentation files (the "Software"), to deal in
//the Software without restriction, including without limitation the rights to
//use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
//of the Software, and to permit persons to whom the Software is furnished to do
//so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: osmformat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Relation_MemberType int32

const (
	Relation_NODE     Relation_MemberType = 0
	Relation_WAY      Relation_MemberType = 1
	Relation_RELATION Relation_MemberType = 2
)

// Enum value maps for Relation_MemberType.
var (
	Relation_MemberType_name = map[int32]string{
		0: "NODE",
		1: "WAY",
		2: "RELATION",
	}
	Relation_MemberType_value = map[string]int32{
		"NODE":     0,
		"WAY":      1,
		"RELATION": 2,
	}
)

func (x Relation_MemberType) Enum() *Relation_MemberType {
	p := new(Relation_MemberType)
	*p = x
	return p
}

func (x Relation_MemberType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Relation_MemberType) Descriptor() protoreflect.EnumDescriptor {
	return file_osmformat_proto_enumTypes[0].Descriptor()
}

func (Relation_MemberType) Type() protoreflect.EnumType {
	return &file_osmformat_proto_enumTypes[0]
}

func (x Relation_MemberType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Relation_MemberType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Relation_MemberType(num)
	return nil
}

// Deprecated: Use Relation_MemberType.Descriptor instead.
func (Relation_MemberType) EnumDescriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{11, 0}
}

type HeaderBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Bbox  *HeaderBBox            `protobuf:"bytes,1,opt,name=bbox" json:"bbox,omitempty"`
	// Additional tags to aid in parsing this dataset
	RequiredFeatures []string `protobuf:"bytes,4,rep,name=required_features,json=requiredFeatures" json:"required_features,omitempty"`
	OptionalFeatures []string `protobuf:"bytes,5,rep,name=optional_features,json=optionalFeatures" json:"optional_features,omitempty"`
	Writingprogram   *string  `protobuf:"bytes,16,opt,name=writingprogram" json:"writingprogram,omitempty"`
	Source           *string  `protobuf:"bytes,17,opt,name=source" json:"source,omitempty"` // From the bbox field.
	// Replication timestamp, expressed in seconds since the epoch,
	// otherwise the same value as in the "timestamp=..." field
	// in the state.txt file used by Osmosis.
	OsmosisReplicationTimestamp *int64 `protobuf:"varint,32,opt,name=osmosis_replication_timestamp,json=osmosisReplicationTimestamp" json:"osmosis_replication_timestamp,omitempty"`
	// Replication sequence number (sequenceNumber in state.txt).
	OsmosisReplicationSequenceNumber *int64 `protobuf:"varint,33,opt,name=osmosis_replication_sequence_number,json=osmosisReplicationSequenceNumber" json:"osmosis_replication_sequence_number,omitempty"`
	// Replication base URL (from Osmosis' configuration.txt file).
	OsmosisReplicationBaseUrl *string `protobuf:"bytes,34,opt,name=osmosis_replication_base_url,json=osmosisReplicationBaseUrl" json:"osmosis_replication_base_url,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HeaderBlock) Reset() {
	*x = HeaderBlock{}
	mi := &file_osmformat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderBlock) ProtoMessage() {}

func (x *HeaderBlock) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderBlock.ProtoReflect.Descriptor instead.
func (*HeaderBlock) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderBlock) GetBbox() *HeaderBBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *HeaderBlock) GetRequiredFeatures() []string {
	if x != nil {
		return x.RequiredFeatures
	}
	return nil
}

func (x *HeaderBlock) GetOptionalFeatures() []string {
	if x != nil {
		return x.OptionalFeatures
	}
	return nil
}

func (x *HeaderBlock) GetWritingprogram() string {
	if x != nil && x.Writingprogram != nil {
		return *x.Writingprogram
	}
	return ""
}

func (x *HeaderBlock) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *HeaderBlock) GetOsmosisReplicationTimestamp() int64 {
	if x != nil && x.OsmosisReplicationTimestamp != nil {
		return *x.OsmosisReplicationTimestamp
	}
	return 0
}

func (x *HeaderBlock) GetOsmosisReplicationSequenceNumber() int64 {
	if x != nil && x.OsmosisReplicationSequenceNumber != nil {
		return *x.OsmosisReplicationSequenceNumber
	}
	return 0
}

func (x *HeaderBlock) GetOsmosisReplicationBaseUrl() string {
	if x != nil && x.OsmosisReplicationBaseUrl != nil {
		return *x.OsmosisReplicationBaseUrl
	}
	return ""
}

type HeaderBBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *int64                 `protobuf:"zigzag64,1,req,name=left" json:"left,omitempty"`
	Right         *int64                 `protobuf:"zigzag64,2,req,name=right" json:"right,omitempty"`
	Top           *int64                 `protobuf:"zigzag64,3,req,name=top" json:"top,omitempty"`
	Bottom        *int64                 `protobuf:"zigzag64,4,req,name=bottom" json:"bottom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderBBox) Reset() {
	*x = HeaderBBox{}
	mi := &file_osmformat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderBBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderBBox) ProtoMessage() {}

func (x *HeaderBBox) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderBBox.ProtoReflect.Descriptor instead.
func (*HeaderBBox) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderBBox) GetLeft() int64 {
	if x != nil && x.Left != nil {
		return *x.Left
	}
	return 0
}

func (x *HeaderBBox) GetRight() int64 {
	if x != nil && x.Right != nil {
		return *x.Right
	}
	return 0
}

func (x *HeaderBBox) GetTop() int64 {
	if x != nil && x.Top != nil {
		return *x.Top
	}
	return 0
}

func (x *HeaderBBox) GetBottom() int64 {
	if x != nil && x.Bottom != nil {
		return *x.Bottom
	}
	return 0
}

type PrimitiveBlock struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Stringtable    *StringTable           `protobuf:"bytes,1,req,name=stringtable" json:"stringtable,omitempty"`
	Primitivegroup []*PrimitiveGroup      `protobuf:"bytes,2,rep,name=primitivegroup" json:"primitivegroup,omitempty"`
	// Granularity, units of nanodegrees, used to store coordinates in this block.
	Granularity *int32 `protobuf:"varint,17,opt,name=granularity,def=100" json:"granularity,omitempty"`
	// Offset value between the output coordinates and the granularity grid in units of nanodegrees.
	LatOffset *int64 `protobuf:"varint,19,opt,name=lat_offset,json=latOffset,def=0" json:"lat_offset,omitempty"`
	LonOffset *int64 `protobuf:"varint,20,opt,name=lon_offset,json=lonOffset,def=0" json:"lon_offset,omitempty"`
	// Granularity of dates, normally represented in units of milliseconds since the 1970 epoch.
	DateGranularity *int32 `protobuf:"varint,18,opt,name=date_granularity,json=dateGranularity,def=1000" json:"date_granularity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for PrimitiveBlock fields.
const (
	Default_PrimitiveBlock_Granularity     = int32(100)
	Default_PrimitiveBlock_LatOffset       = int64(0)
	Default_PrimitiveBlock_LonOffset       = int64(0)
	Default_PrimitiveBlock_DateGranularity = int32(1000)
)

func (x *PrimitiveBlock) Reset() {
	*x = PrimitiveBlock{}
	mi := &file_osmformat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimitiveBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimitiveBlock) ProtoMessage() {}

func (x *PrimitiveBlock) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimitiveBlock.ProtoReflect.Descriptor instead.
func (*PrimitiveBlock) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{2}
}

func (x *PrimitiveBlock) GetStringtable() *StringTable {
	if x != nil {
		return x.Stringtable
	}
	return nil
}

func (x *PrimitiveBlock) GetPrimitivegroup() []*PrimitiveGroup {
	if x != nil {
		return x.Primitivegroup
	}
	return nil
}

func (x *PrimitiveBlock) GetGranularity() int32 {
	if x != nil && x.Granularity != nil {
		return *x.Granularity
	}
	return Default_PrimitiveBlock_Granularity
}

func (x *PrimitiveBlock) GetLatOffset() int64 {
	if x != nil && x.LatOffset != nil {
		return *x.LatOffset
	}
	return Default_PrimitiveBlock_LatOffset
}

func (x *PrimitiveBlock) GetLonOffset() int64 {
	if x != nil && x.LonOffset != nil {
		return *x.LonOffset
	}
	return Default_PrimitiveBlock_LonOffset
}

func (x *PrimitiveBlock) GetDateGranularity() int32 {
	if x != nil && x.DateGranularity != nil {
		return *x.DateGranularity
	}
	return Default_PrimitiveBlock_DateGranularity
}

// Group of OSMPrimitives. All primitives in a group must be the same type.
type PrimitiveGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	Dense         *DenseNodes            `protobuf:"bytes,2,opt,name=dense" json:"dense,omitempty"`
	Ways          []*Way                 `protobuf:"bytes,3,rep,name=ways" json:"ways,omitempty"`
	Relations     []*Relation            `protobuf:"bytes,4,rep,name=relations" json:"relations,omitempty"`
	Changesets    []*ChangeSet           `protobuf:"bytes,5,rep,name=changesets" json:"changesets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimitiveGroup) Reset() {
	*x = PrimitiveGroup{}
	mi := &file_osmformat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimitiveGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimitiveGroup) ProtoMessage() {}

func (x *PrimitiveGroup) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimitiveGroup.ProtoReflect.Descriptor instead.
func (*PrimitiveGroup) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{3}
}

func (x *PrimitiveGroup) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *PrimitiveGroup) GetDense() *DenseNodes {
	if x != nil {
		return x.Dense
	}
	return nil
}

func (x *PrimitiveGroup) GetWays() []*Way {
	if x != nil {
		return x.Ways
	}
	return nil
}

func (x *PrimitiveGroup) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *PrimitiveGroup) GetChangesets() []*ChangeSet {
	if x != nil {
		return x.Changesets
	}
	return nil
}

// * String table, contains the common strings in each block.
//
// Note that we reserve index '0' as a delimiter, so the entry at that
// index in the table is ALWAYS blank and unused.
type StringTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             [][]byte               `protobuf:"bytes,1,rep,name=s" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTable) Reset() {
	*x = StringTable{}
	mi := &file_osmformat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTable) ProtoMessage() {}

func (x *StringTable) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTable.ProtoReflect.Descriptor instead.
func (*StringTable) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{4}
}

func (x *StringTable) GetS() [][]byte {
	if x != nil {
		return x.S
	}
	return nil
}

// Optional metadata that may be included into each primitive.
type Info struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   *int32                 `protobuf:"varint,1,opt,name=version,def=-1" json:"version,omitempty"`
	Timestamp *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Changeset *int64                 `protobuf:"varint,3,opt,name=changeset" json:"changeset,omitempty"`
	Uid       *int32                 `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	UserSid   *uint32                `protobuf:"varint,5,opt,name=user_sid,json=userSid" json:"user_sid,omitempty"` // String IDs
	// The visible flag is used to store history information. It indicates that
	// the current object version has been created by a delete operation on the
	// OSM API.
	// When a writer sets this flag, it MUST add a required_features tag with
	// value "HistoricalInformation" to the HeaderBlock.
	// If this flag is not available for some object it MUST be assumed to be
	// true if the file has the required_features tag "HistoricalInformation"
	// set.
	Visible       *bool `protobuf:"varint,6,opt,name=visible" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Info fields.
const (
	Default_Info_Version = int32(-1)
)

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_osmformat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{5}
}

func (x *Info) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return Default_Info_Version
}

func (x *Info) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Info) GetChangeset() int64 {
	if x != nil && x.Changeset != nil {
		return *x.Changeset
	}
	return 0
}

func (x *Info) GetUid() int32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *Info) GetUserSid() uint32 {
	if x != nil && x.UserSid != nil {
		return *x.UserSid
	}
	return 0
}

func (x *Info) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

// * Optional metadata that may be included into each primitive. Special dense format used in DenseNodes.
type DenseInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   []int32                `protobuf:"varint,1,rep,packed,name=version" json:"version,omitempty"`
	Timestamp []int64                `protobuf:"zigzag64,2,rep,packed,name=timestamp" json:"timestamp,omitempty"`            // DELTA coded
	Changeset []int64                `protobuf:"zigzag64,3,rep,packed,name=changeset" json:"changeset,omitempty"`            // DELTA coded
	Uid       []int32                `protobuf:"zigzag32,4,rep,packed,name=uid" json:"uid,omitempty"`                        // DELTA coded
	UserSid   []int32                `protobuf:"zigzag32,5,rep,packed,name=user_sid,json=userSid" json:"user_sid,omitempty"` // String IDs for usernames. DELTA coded
	// The visible flag is used to store history information. It indicates that
	// the current object version has been created by a delete operation on the
	// OSM API.
	// When a writer sets this flag, it MUST add a required_features tag with
	// value "HistoricalInformation" to the HeaderBlock.
	// If this flag is not available for some object it MUST be assumed to be
	// true if the file has the required_features tag "HistoricalInformation"
	// set.
	Visible       []bool `protobuf:"varint,6,rep,packed,name=visible" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenseInfo) Reset() {
	*x = DenseInfo{}
	mi := &file_osmformat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenseInfo) ProtoMessage() {}

func (x *DenseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenseInfo.ProtoReflect.Descriptor instead.
func (*DenseInfo) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{6}
}

func (x *DenseInfo) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DenseInfo) GetTimestamp() []int64 {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DenseInfo) GetChangeset() []int64 {
	if x != nil {
		return x.Changeset
	}
	return nil
}

func (x *DenseInfo) GetUid() []int32 {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *DenseInfo) GetUserSid() []int32 {
	if x != nil {
		return x.UserSid
	}
	return nil
}

func (x *DenseInfo) GetVisible() []bool {
	if x != nil {
		return x.Visible
	}
	return nil
}

// This is kept for backwards compatibility but not used anywhere.
type ChangeSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSet) Reset() {
	*x = ChangeSet{}
	mi := &file_osmformat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSet) ProtoMessage() {}

func (x *ChangeSet) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSet.ProtoReflect.Descriptor instead.
func (*ChangeSet) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeSet) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *int64                 `protobuf:"zigzag64,1,req,name=id" json:"id,omitempty"`
	// Parallel arrays.
	Keys          []uint32 `protobuf:"varint,2,rep,packed,name=keys" json:"keys,omitempty"` // String IDs.
	Vals          []uint32 `protobuf:"varint,3,rep,packed,name=vals" json:"vals,omitempty"` // String IDs.
	Info          *Info    `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`         // May be omitted in omitmeta
	Lat           *int64   `protobuf:"zigzag64,8,req,name=lat" json:"lat,omitempty"`
	Lon           *int64   `protobuf:"zigzag64,9,req,name=lon" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_osmformat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{8}
}

func (x *Node) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Node) GetKeys() []uint32 {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Node) GetVals() []uint32 {
	if x != nil {
		return x.Vals
	}
	return nil
}

func (x *Node) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Node) GetLat() int64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Node) GetLon() int64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

type DenseNodes struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        []int64                `protobuf:"zigzag64,1,rep,packed,name=id" json:"id,omitempty"` // DELTA coded
	Denseinfo *DenseInfo             `protobuf:"bytes,5,opt,name=denseinfo" json:"denseinfo,omitempty"`
	Lat       []int64                `protobuf:"zigzag64,8,rep,packed,name=lat" json:"lat,omitempty"` // DELTA coded
	Lon       []int64                `protobuf:"zigzag64,9,rep,packed,name=lon" json:"lon,omitempty"` // DELTA coded
	// Special packing of keys and vals into one array. May be empty if all nodes in this block are tagless.
	KeysVals      []int32 `protobuf:"varint,10,rep,packed,name=keys_vals,json=keysVals" json:"keys_vals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenseNodes) Reset() {
	*x = DenseNodes{}
	mi := &file_osmformat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenseNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenseNodes) ProtoMessage() {}

func (x *DenseNodes) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenseNodes.ProtoReflect.Descriptor instead.
func (*DenseNodes) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{9}
}

func (x *DenseNodes) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DenseNodes) GetDenseinfo() *DenseInfo {
	if x != nil {
		return x.Denseinfo
	}
	return nil
}

func (x *DenseNodes) GetLat() []int64 {
	if x != nil {
		return x.Lat
	}
	return nil
}

func (x *DenseNodes) GetLon() []int64 {
	if x != nil {
		return x.Lon
	}
	return nil
}

func (x *DenseNodes) GetKeysVals() []int32 {
	if x != nil {
		return x.KeysVals
	}
	return nil
}

type Way struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	// Parallel arrays.
	Keys []uint32 `protobuf:"varint,2,rep,packed,name=keys" json:"keys,omitempty"`
	Vals []uint32 `protobuf:"varint,3,rep,packed,name=vals" json:"vals,omitempty"`
	Info *Info    `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	Refs []int64  `protobuf:"zigzag64,8,rep,packed,name=refs" json:"refs,omitempty"` // DELTA coded
	// The following two fields are optional. They are only used in a special
	// format where node locations are also added to the ways. This makes the
	// files larger, but allows creating way geometries directly.
	//
	// If this is used, you MUST set the optional_features tag "LocationsOnWays"
	// and the number of values in refs, lat, and lon MUST be the same.
	Lat           []int64 `protobuf:"zigzag64,9,rep,packed,name=lat" json:"lat,omitempty"`  // DELTA coded, optional
	Lon           []int64 `protobuf:"zigzag64,10,rep,packed,name=lon" json:"lon,omitempty"` // DELTA coded, optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Way) Reset() {
	*x = Way{}
	mi := &file_osmformat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Way) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Way) ProtoMessage() {}

func (x *Way) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Way.ProtoReflect.Descriptor instead.
func (*Way) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{10}
}

func (x *Way) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Way) GetKeys() []uint32 {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Way) GetVals() []uint32 {
	if x != nil {
		return x.Vals
	}
	return nil
}

func (x *Way) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Way) GetRefs() []int64 {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *Way) GetLat() []int64 {
	if x != nil {
		return x.Lat
	}
	return nil
}

func (x *Way) GetLon() []int64 {
	if x != nil {
		return x.Lon
	}
	return nil
}

type Relation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	// Parallel arrays.
	Keys []uint32 `protobuf:"varint,2,rep,packed,name=keys" json:"keys,omitempty"`
	Vals []uint32 `protobuf:"varint,3,rep,packed,name=vals" json:"vals,omitempty"`
	Info *Info    `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	// Parallel arrays
	RolesSid      []int32               `protobuf:"varint,8,rep,packed,name=roles_sid,json=rolesSid" json:"roles_sid,omitempty"` // This should have been defined as uint32 for consistency, but it is now too late to change it
	Memids        []int64               `protobuf:"zigzag64,9,rep,packed,name=memids" json:"memids,omitempty"`                   // DELTA encoded
	Types         []Relation_MemberType `protobuf:"varint,10,rep,packed,name=types,enum=OSMPBF.Relation_MemberType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_osmformat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_osmformat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_osmformat_proto_rawDescGZIP(), []int{11}
}

func (x *Relation) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Relation) GetKeys() []uint32 {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Relation) GetVals() []uint32 {
	if x != nil {
		return x.Vals
	}
	return nil
}

func (x *Relation) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Relation) GetRolesSid() []int32 {
	if x != nil {
		return x.RolesSid
	}
	return nil
}

func (x *Relation) GetMemids() []int64 {
	if x != nil {
		return x.Memids
	}
	return nil
}

func (x *Relation) GetTypes() []Relation_MemberType {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_osmformat_proto protoreflect.FileDescriptor

const file_osmformat_proto_rawDesc = "" +
	"\n" +
	"\x0fosmformat.proto\x12\x06OSMPBF\"\xa3\x03\n" +
	"\vHeaderBlock\x12&\n" +
	"\x04bbox\x18\x01 \x01(\v2\x12.OSMPBF.HeaderBBoxR\x04bbox\x12+\n" +
	"\x11required_features\x18\x04 \x03(\tR\x10requiredFeatures\x12+\n" +
	"\x11optional_features\x18\x05 \x03(\tR\x10optionalFeatures\x12&\n" +
	"\x0ewritingprogram\x18\x10 \x01(\tR\x0ewritingprogram\x12\x16\n" +
	"\x06source\x18\x11 \x01(\tR\x06source\x12B\n" +
	"\x1dosmosis_replication_timestamp\x18  \x01(\x03R\x1bosmosisReplicationTimestamp\x12M\n" +
	"#osmosis_replication_sequence_number\x18! \x01(\x03R osmosisReplicationSequenceNumber\x12?\n" +
	"\x1cosmosis_replication_base_url\x18\" \x01(\tR\x19osmosisReplicationBaseUrl\"`\n" +
	"\n" +
	"HeaderBBox\x12\x12\n" +
	"\x04left\x18\x01 \x02(\x12R\x04left\x12\x14\n" +
	"\x05right\x18\x02 \x02(\x12R\x05right\x12\x10\n" +
	"\x03top\x18\x03 \x02(\x12R\x03top\x12\x16\n" +
	"\x06bottom\x18\x04 \x02(\x12R\x06bottom\"\xa3\x02\n" +
	"\x0ePrimitiveBlock\x125\n" +
	"\vstringtable\x18\x01 \x02(\v2\x13.OSMPBF.StringTableR\vstringtable\x12>\n" +
	"\x0eprimitivegroup\x18\x02 \x03(\v2\x16.OSMPBF.PrimitiveGroupR\x0eprimitivegroup\x12%\n" +
	"\vgranularity\x18\x11 \x01(\x05:\x03100R\vgranularity\x12 \n" +
	"\n" +
	"lat_offset\x18\x13 \x01(\x03:\x010R\tlatOffset\x12 \n" +
	"\n" +
	"lon_offset\x18\x14 \x01(\x03:\x010R\tlonOffset\x12/\n" +
	"\x10date_granularity\x18\x12 \x01(\x05:\x041000R\x0fdateGranularity\"\xe2\x01\n" +
	"\x0ePrimitiveGroup\x12\"\n" +
	"\x05nodes\x18\x01 \x03(\v2\f.OSMPBF.NodeR\x05nodes\x12(\n" +
	"\x05dense\x18\x02 \x01(\v2\x12.OSMPBF.DenseNodesR\x05dense\x12\x1f\n" +
	"\x04ways\x18\x03 \x03(\v2\v.OSMPBF.WayR\x04ways\x12.\n" +
	"\trelations\x18\x04 \x03(\v2\x10.OSMPBF.RelationR\trelations\x121\n" +
	"\n" +
	"changesets\x18\x05 \x03(\v2\x11.OSMPBF.ChangeSetR\n" +
	"changesets\"\x1b\n" +
	"\vStringTable\x12\f\n" +
	"\x01s\x18\x01 \x03(\fR\x01s\"\xa7\x01\n" +
	"\x04Info\x12\x1c\n" +
	"\aversion\x18\x01 \x01(\x05:\x02-1R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tchangeset\x18\x03 \x01(\x03R\tchangeset\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x05R\x03uid\x12\x19\n" +
	"\buser_sid\x18\x05 \x01(\rR\auserSid\x12\x18\n" +
	"\avisible\x18\x06 \x01(\bR\avisible\"\xc0\x01\n" +
	"\tDenseInfo\x12\x1c\n" +
	"\aversion\x18\x01 \x03(\x05B\x02\x10\x01R\aversion\x12 \n" +
	"\ttimestamp\x18\x02 \x03(\x12B\x02\x10\x01R\ttimestamp\x12 \n" +
	"\tchangeset\x18\x03 \x03(\x12B\x02\x10\x01R\tchangeset\x12\x14\n" +
	"\x03uid\x18\x04 \x03(\x11B\x02\x10\x01R\x03uid\x12\x1d\n" +
	"\buser_sid\x18\x05 \x03(\x11B\x02\x10\x01R\auserSid\x12\x1c\n" +
	"\avisible\x18\x06 \x03(\bB\x02\x10\x01R\avisible\"\x1b\n" +
	"\tChangeSet\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\"\x8c\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x12R\x02id\x12\x16\n" +
	"\x04keys\x18\x02 \x03(\rB\x02\x10\x01R\x04keys\x12\x16\n" +
	"\x04vals\x18\x03 \x03(\rB\x02\x10\x01R\x04vals\x12 \n" +
	"\x04info\x18\x04 \x01(\v2\f.OSMPBF.InfoR\x04info\x12\x10\n" +
	"\x03lat\x18\b \x02(\x12R\x03lat\x12\x10\n" +
	"\x03lon\x18\t \x02(\x12R\x03lon\"\x9e\x01\n" +
	"\n" +
	"DenseNodes\x12\x12\n" +
	"\x02id\x18\x01 \x03(\x12B\x02\x10\x01R\x02id\x12/\n" +
	"\tdenseinfo\x18\x05 \x01(\v2\x11.OSMPBF.DenseInfoR\tdenseinfo\x12\x14\n" +
	"\x03lat\x18\b \x03(\x12B\x02\x10\x01R\x03lat\x12\x14\n" +
	"\x03lon\x18\t \x03(\x12B\x02\x10\x01R\x03lon\x12\x1f\n" +
	"\tkeys_vals\x18\n" +
	" \x03(\x05B\x02\x10\x01R\bkeysVals\"\xab\x01\n" +
	"\x03Way\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\x12\x16\n" +
	"\x04keys\x18\x02 \x03(\rB\x02\x10\x01R\x04keys\x12\x16\n" +
	"\x04vals\x18\x03 \x03(\rB\x02\x10\x01R\x04vals\x12 \n" +
	"\x04info\x18\x04 \x01(\v2\f.OSMPBF.InfoR\x04info\x12\x16\n" +
	"\x04refs\x18\b \x03(\x12B\x02\x10\x01R\x04refs\x12\x14\n" +
	"\x03lat\x18\t \x03(\x12B\x02\x10\x01R\x03lat\x12\x14\n" +
	"\x03lon\x18\n" +
	" \x03(\x12B\x02\x10\x01R\x03lon\"\x8f\x02\n" +
	"\bRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\x12\x16\n" +
	"\x04keys\x18\x02 \x03(\rB\x02\x10\x01R\x04keys\x12\x16\n" +
	"\x04vals\x18\x03 \x03(\rB\x02\x10\x01R\x04vals\x12 \n" +
	"\x04info\x18\x04 \x01(\v2\f.OSMPBF.InfoR\x04info\x12\x1f\n" +
	"\troles_sid\x18\b \x03(\x05B\x02\x10\x01R\brolesSid\x12\x1a\n" +
	"\x06memids\x18\t \x03(\x12B\x02\x10\x01R\x06memids\x125\n" +
	"\x05types\x18\n" +
	" \x03(\x0e2\x1b.OSMPBF.Relation.MemberTypeB\x02\x10\x01R\x05types\"-\n" +
	"\n" +
	"MemberType\x12\b\n" +
	"\x04NODE\x10\x00\x12\a\n" +
	"\x03WAY\x10\x01\x12\f\n" +
	"\bRELATION\x10\x02BD\n" +
	"\rcrosby.binaryZ3github.com/your-map/mbtiles-tool/internal/osm/proto"

var (
	file_osmformat_proto_rawDescOnce sync.Once
	file_osmformat_proto_rawDescData []byte
)

func file_osmformat_proto_rawDescGZIP() []byte {
	file_osmformat_proto_rawDescOnce.Do(func() {
		file_osmformat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osmformat_proto_rawDesc), len(file_osmformat_proto_rawDesc)))
	})
	return file_osmformat_proto_rawDescData
}

var file_osmformat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osmformat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_osmformat_proto_goTypes = []any{
	(Relation_MemberType)(0), // 0: OSMPBF.Relation.MemberType
	(*HeaderBlock)(nil),      // 1: OSMPBF.HeaderBlock
	(*HeaderBBox)(nil),       // 2: OSMPBF.HeaderBBox
	(*PrimitiveBlock)(nil),   // 3: OSMPBF.PrimitiveBlock
	(*PrimitiveGroup)(nil),   // 4: OSMPBF.PrimitiveGroup
	(*StringTable)(nil),      // 5: OSMPBF.StringTable
	(*Info)(nil),             // 6: OSMPBF.Info
	(*DenseInfo)(nil),        // 7: OSMPBF.DenseInfo
	(*ChangeSet)(nil),        // 8: OSMPBF.ChangeSet
	(*Node)(nil),             // 9: OSMPBF.Node
	(*DenseNodes)(nil),       // 10: OSMPBF.DenseNodes
	(*Way)(nil),              // 11: OSMPBF.Way
	(*Relation)(nil),         // 12: OSMPBF.Relation
}
var file_osmformat_proto_depIdxs = []int32{
	2,  // 0: OSMPBF.HeaderBlock.bbox:type_name -> OSMPBF.HeaderBBox
	5,  // 1: OSMPBF.PrimitiveBlock.stringtable:type_name -> OSMPBF.StringTable
	4,  // 2: OSMPBF.PrimitiveBlock.primitivegroup:type_name -> OSMPBF.PrimitiveGroup
	9,  // 3: OSMPBF.PrimitiveGroup.nodes:type_name -> OSMPBF.Node
	10, // 4: OSMPBF.PrimitiveGroup.dense:type_name -> OSMPBF.DenseNodes
	11, // 5: OSMPBF.PrimitiveGroup.ways:type_name -> OSMPBF.Way
	12, // 6: OSMPBF.PrimitiveGroup.relations:type_name -> OSMPBF.Relation
	8,  // 7: OSMPBF.PrimitiveGroup.changesets:type_name -> OSMPBF.ChangeSet
	6,  // 8: OSMPBF.Node.info:type_name -> OSMPBF.Info
	7,  // 9: OSMPBF.DenseNodes.denseinfo:type_name -> OSMPBF.DenseInfo
	6,  // 10: OSMPBF.Way.info:type_name -> OSMPBF.Info
	6,  // 11: OSMPBF.Relation.info:type_name -> OSMPBF.Info
	0,  // 12: OSMPBF.Relation.types:type_name -> OSMPBF.Relation.MemberType
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_osmformat_proto_init() }
func file_osmformat_proto_init() {
	if File_osmformat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osmformat_proto_rawDesc), len(file_osmformat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osmformat_proto_goTypes,
		DependencyIndexes: file_osmformat_proto_depIdxs,
		EnumInfos:         file_osmformat_proto_enumTypes,
		MessageInfos:      file_osmformat_proto_msgTypes,
	}.Build()
	File_osmformat_proto = out.File
	file_osmformat_proto_goTypes = nil
	file_osmformat_proto_depIdxs = nil
}
