version: 2

env:
  - GO111MODULE=on

project_name: cli

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
    main: "./cmd/{{ .ProjectName }}"

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

nfpms:
  - package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    description: "{{.ProjectName}} example description"
    maintainer: Denis Korbakov <korbakovd009@gmail.com>
    license: MIT
    vendor: Deniskorbakov
    bindir: /usr/bin
    section: utils
    mtime: "{{ .CommitDate }}"
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - git
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

release:
  draft: true
  prerelease: auto
  name_template: "{{.Version}}"